#!/bin/bash

set -e

apt-mark hold apt gnupg adduser passwd libsemanage1
echo "Yes, do as I say!" | apt-get purge \
    e2fslibs \
    insserv \
    libcap2-bin \
    libkmod2 \
    libmount1 \
    libncursesw5 \
    libprocps4 \
    libsmartcols1 \
    libsystemd0 \
    libudev1 \
    ncurses-base \
    ncurses-bin \
    locales \
    sysv-rc \
    sysvinit-utils \
    tzdata

apt-get autoremove -y && \
    apt-get clean -y && \
    tar -czf /usr/share/copyrights.tar.gz /usr/share/common-licenses /usr/share/doc/*/copyright && \
    rm -rf \
        /usr/share/doc \
        /usr/share/man \
        /usr/share/info \
        /usr/share/locale \
        /var/lib/apt/lists/* \
        /var/log/* \
        /var/cache/debconf/* \
        /usr/share/common-licenses* \
        ~/.bashrc \
        /etc/systemd \
        /lib/lsb \
        /lib/udev \
        /usr/lib/x86_64-linux-gnu/gconv/IBM* \
        /usr/lib/x86_64-linux-gnu/gconv/EBC* && \
    mkdir -p /usr/share/man/man1 /usr/share/man/man2 \
        /usr/share/man/man3 /usr/share/man/man4 \
        /usr/share/man/man5 /usr/share/man/man6 \
        /usr/share/man/man7 /usr/share/man/man8

